# This rule is not used by the project kubernetes-ip-tracker itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the networking.learntosolveit.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubernetes-ip-tracker
    app.kubernetes.io/managed-by: kustomize
  name: podtracker-editor-role
rules:
- apiGroups:
  - networking.learntosolveit.com
  resources:
  - podtrackers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.learntosolveit.com
  resources:
  - podtrackers/status
  verbs:
  - get
