---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-ip-tracker-agent
  namespace: kubernetes-ip-tracker-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-ip-tracker-agent-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.learntosolveit.com
  resources:
  - podtrackers
  verbs:
  - get
  - list
  - update
  - patch
- apiGroups:
  - networking.learntosolveit.com
  resources:
  - podtrackers/status
  verbs:
  - get
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-ip-tracker-agent-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-ip-tracker-agent-role
subjects:
- kind: ServiceAccount
  name: pod-ip-tracker-agent
  namespace: kubernetes-ip-tracker-system
